# Generated by Django 4.1.7 on 2024-09-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devishop', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
