# Generated by Django 4.1.7 on 2024-09-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devishop', '0004_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
